name: Deployment CI

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set APP_NAME environment variable
        run: echo "APP_NAME=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      -
        name: Checkout repository
        uses: actions/checkout@v3
      # -
      #   name: Create env file
      #   run: echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" > ./.env
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push image to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:latest
      -
        name: Configure kubernetes.yml
        run: sed -i "s/\$APP_NAME/${{ env.APP_NAME }}/g" ./kubernetes.yml && sed -i "s/\$DOCKERHUB_USERNAME/${{ secrets.DOCKERHUB_USERNAME }}/g" ./kubernetes.yml
      -
        name: Debug
        run: cat ./kubernetes.yml
      -
        name: Create firebase_credentials.json
        run: echo '${{ secrets.FIREBASE_CREDENTIALS }}' >> ./src/firebase_credentials.json
      -
        name: Delete deployment from okteto
        uses: steebchen/kubectl@v2.0.0
        continue-on-error: true
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: delete -f ./kubernetes.yml
      -
        name: Apply deployment to okteto
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: apply -f ./kubernetes.yml
